package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ivanhoe/apus_cli/internal/preflight"
	"github.com/ivanhoe/apus_cli/internal/terminal"
	"github.com/ivanhoe/apus_cli/internal/xcode"
	"github.com/spf13/cobra"
)

var removeCmd = &cobra.Command{
	Use:   "remove",
	Short: "Remove Apus from an existing Xcode project (reverses apus init)",
	Long: `apus remove undoes what apus init did:
removes the Apus Swift Package dependency, the injected import and start() call,
and the AGENTS.md file if it was generated by Apus.`,
	Args: cobra.NoArgs,
	RunE: runRemove,
}

func runRemove(_ *cobra.Command, _ []string) error {
	if err := preflight.Validate(preflight.ScopeInit); err != nil {
		return err
	}

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}

	info, err := xcode.DetectProject(cwd)
	if err != nil {
		terminal.Fatal("project detection failed", err)
		return err
	}

	// Check if Apus is actually integrated
	hasApus, _ := xcode.HasApusIntegration(cwd)
	pbxPath := filepath.Join(info.ProjectPath, "project.pbxproj")
	pbxRaw, _ := os.ReadFile(pbxPath)
	pbxHasApus := strings.Contains(string(pbxRaw), "github.com/ivanhoe/apus")

	if !hasApus && !pbxHasApus {
		terminal.Info("Apus is not integrated in this project — nothing to remove.")
		return nil
	}

	terminal.Detected(filepath.Base(info.ProjectPath), info.Target)

	backup, err := createProjectBackup(cwd, backupCandidates(info))
	if err != nil {
		return fmt.Errorf("create backup: %w", err)
	}
	if backup.fileCount > 0 {
		terminal.Info("Backup created: " + backup.dir)
	}

	p := terminal.NewProgress(3)

	// ── Step 1: Un-inject Swift code ──
	{
		entryLabel := "app entry point"
		if info.EntryFile != "" {
			entryLabel = filepath.Base(info.EntryFile)
		}
		done := p.Start("Removing Apus from " + entryLabel)
		if info.EntryFile != "" {
			err = xcode.UninjectApus(info.EntryFile)
		}
		done(err)
		if err != nil {
			terminal.Fatal("Swift un-injection failed", err)
			if rollbackErr := backup.restore(); rollbackErr != nil {
				return fmt.Errorf("swift un-injection failed: %w (rollback failed: %v)", err, rollbackErr)
			}
			return fmt.Errorf("swift un-injection failed; backed-up files restored: %w", err)
		}
	}

	// ── Step 2: Remove from .pbxproj ──
	{
		done := p.Start("Removing Apus from project.pbxproj")
		err = xcode.RemoveApusDependency(info.ProjectPath, info.Target)
		done(err)
		if err != nil {
			terminal.Fatal("pbxproj modification failed", err)
			if rollbackErr := backup.restore(); rollbackErr != nil {
				return fmt.Errorf("pbxproj modification failed: %w (rollback failed: %v)", err, rollbackErr)
			}
			return fmt.Errorf("pbxproj modification failed; backed-up files restored: %w", err)
		}
	}

	// ── Step 3: Delete AGENTS.md ──
	{
		done := p.Start("Removing AGENTS.md")
		err = removeAgentsMD(cwd)
		done(err)
		if err != nil {
			terminal.Fatal("AGENTS.md removal failed", err)
			// Non-fatal
		}
	}

	terminal.RemoveSuccess(info.ProjectName)
	return nil
}

func removeAgentsMD(dir string) error {
	path := filepath.Join(dir, "AGENTS.md")
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !strings.Contains(string(raw), "Apus runs at") {
		return nil // not ours
	}
	return os.Remove(path)
}
