package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/ivanhoe/apus_cli/internal/preflight"
	"github.com/ivanhoe/apus_cli/internal/terminal"
	"github.com/ivanhoe/apus_cli/internal/xcode"
	"github.com/spf13/cobra"
)

var removeDryRun bool
var removeJSON bool
var removePath string
var removeTarget string

var removeCmd = &cobra.Command{
	Use:   "remove",
	Short: "Remove Apus from an existing Xcode project (reverses apus init)",
	Long: `apus remove undoes what apus init did:
removes the Apus Swift Package dependency, the injected import and start() call,
and the AGENTS.md file if it was generated by Apus.`,
	Args: cobra.NoArgs,
	RunE: runRemove,
}

func init() {
	removeCmd.Flags().StringVar(&removePath, "path", "", "Project directory to inspect instead of the current working directory")
	removeCmd.Flags().BoolVar(&removeDryRun, "dry-run", false, "Show what would change without modifying any files")
	removeCmd.Flags().BoolVar(&removeJSON, "json", false, "Print the remove result as JSON")
	removeCmd.Flags().StringVar(&removeTarget, "target", "", "App target to modify when the project contains multiple app targets")
}

func runRemove(_ *cobra.Command, _ []string) error {
	projectDir, err := resolveCommandPath(removePath)
	if err != nil {
		err = usageError(err)
		if removeJSON {
			return writeJSONResult(struct {
				Mode  string `json:"mode"`
				Error string `json:"error"`
			}{
				Mode:  removeMode(),
				Error: err.Error(),
			}, err)
		}
		return err
	}

	report := preflight.RunWithOptions(preflight.Options{
		Scope:      preflight.ScopeInit,
		ProjectDir: projectDir,
		Target:     removeTarget,
	})
	if report.HasFailures() {
		reportErr := classifyPreflightReportError(report)
		if removeJSON {
			return writeJSONResult(struct {
				Mode   string           `json:"mode"`
				Report preflight.Report `json:"report"`
				Error  string           `json:"error"`
			}{
				Mode:   removeMode(),
				Report: report,
				Error:  reportErr.Error(),
			}, reportErr)
		}
		terminal.Fatal("preflight checks failed", reportErr)
		return markPrinted(reportErr)
	}

	info := report.Project.Info
	if info == nil {
		return unsupportedError(fmt.Errorf("preflight succeeded without project detection details"))
	}

	// Check if Apus is actually integrated
	hasApus, _ := xcode.HasApusIntegration(projectDir)
	dependencyState, depErr := xcode.DetectApusDependency(info.ProjectPath)
	if depErr != nil {
		err = projectError(depErr)
		if removeJSON {
			return writeJSONResult(struct {
				Mode    string       `json:"mode"`
				Project *jsonProject `json:"project"`
				Error   string       `json:"error"`
			}{
				Mode:    removeMode(),
				Project: jsonProjectFromInfo(projectDir, info),
				Error:   err.Error(),
			}, err)
		}
		return err
	}
	pbxHasApus := dependencyState.Any()

	hasAgents, _ := readManagedAgentsFile(projectDir)
	plan := buildRemovePlan(projectDir, info, hasApus, pbxHasApus, hasAgents)

	if !hasApus && !pbxHasApus && !hasAgents {
		if removeJSON {
			return writeJSONResult(struct {
				Mode    string     `json:"mode"`
				Plan    removePlan `json:"plan"`
				Applied bool       `json:"applied"`
			}{
				Mode:    removeMode(),
				Plan:    plan,
				Applied: false,
			}, nil)
		}
		terminal.Info("Apus is not integrated in this project — nothing to remove.")
		return nil
	}

	// ── Dry run ──
	if removeDryRun {
		return dryRunRemove(plan, removeJSON)
	}

	if !removeJSON {
		terminal.Detected(filepath.Base(info.ProjectPath), info.Target)
		printPreflightWarnings(report)
	}

	backup, err := createProjectBackup(projectDir, backupCandidates(info))
	if err != nil {
		return mutationError(fmt.Errorf("create backup: %w", err))
	}
	if backup.fileCount > 0 && !removeJSON {
		terminal.Info("Backup created: " + backup.dir)
	}

	var changes []terminal.FileChange
	p := terminal.NewProgress(3)

	// ── Step 1: Un-inject Swift code ──
	{
		entryLabel := "app entry point"
		if info.EntryFile != "" {
			entryLabel = filepath.Base(info.EntryFile)
		}
		done := func(error) {}
		if !removeJSON {
			done = p.Start("Removing Apus from " + entryLabel)
		}
		if info.EntryFile != "" {
			entryBefore := countLines(info.EntryFile)
			err = xcode.UninjectApus(info.EntryFile)
			done(err)
			if err != nil {
				if !removeJSON {
					terminal.Fatal("Swift un-injection failed", err)
				}
				if rollbackErr := backup.restore(); rollbackErr != nil {
					if !removeJSON {
						terminal.Info("Rollback failed: " + rollbackErr.Error())
					}
					return markPrinted(rollbackError(fmt.Errorf("swift un-injection failed: %w", err)))
				}
				return markPrinted(mutationError(fmt.Errorf("swift un-injection failed; backed-up files restored: %w", err)))
			}
			entryAfter := countLines(info.EntryFile)
			if entryAfter != entryBefore {
				changes = append(changes, terminal.FileChange{Action: "modified", File: filepath.Base(info.EntryFile), Detail: fmt.Sprintf("%d lines", entryAfter-entryBefore)})
			}
		} else {
			done(nil)
		}
	}

	// ── Step 2: Remove from .pbxproj ──
	{
		pbxBefore := readFileSize(filepath.Join(info.ProjectPath, "project.pbxproj"))
		done := func(error) {}
		if !removeJSON {
			done = p.Start("Removing Apus from project.pbxproj")
		}
		err = xcode.RemoveApusDependency(info.ProjectPath, info.Target)
		done(err)
		if err != nil {
			if !removeJSON {
				terminal.Fatal("pbxproj modification failed", err)
			}
			if rollbackErr := backup.restore(); rollbackErr != nil {
				if !removeJSON {
					terminal.Info("Rollback failed: " + rollbackErr.Error())
				}
				return markPrinted(rollbackError(fmt.Errorf("pbxproj modification failed: %w", err)))
			}
			return markPrinted(mutationError(fmt.Errorf("pbxproj modification failed; backed-up files restored: %w", err)))
		}
		pbxAfter := readFileSize(filepath.Join(info.ProjectPath, "project.pbxproj"))
		if pbxAfter != pbxBefore {
			changes = append(changes, terminal.FileChange{Action: "modified", File: "project.pbxproj", Detail: fmt.Sprintf("%d bytes", pbxAfter-pbxBefore)})
		}
	}

	// ── Step 3: Delete AGENTS.md ──
	{
		done := func(error) {}
		if !removeJSON {
			done = p.Start("Removing AGENTS.md")
		}
		err = removeAgentsMD(projectDir)
		done(err)
		if err != nil {
			if !removeJSON {
				terminal.Fatal("AGENTS.md removal failed", err)
			}
			// Non-fatal
		} else if hasAgents {
			changes = append(changes, terminal.FileChange{Action: "deleted", File: "AGENTS.md", Detail: "removed"})
		}
	}

	if removeJSON {
		return writeJSONResult(struct {
			Mode    string       `json:"mode"`
			Plan    removePlan   `json:"plan"`
			Applied bool         `json:"applied"`
			Changes []jsonAction `json:"changes,omitempty"`
		}{
			Mode:    removeMode(),
			Plan:    plan,
			Applied: true,
			Changes: jsonActionsFromChanges(changes),
		}, nil)
	}

	terminal.Summary(changes)
	terminal.RemoveSuccess(info.ProjectName)
	return nil
}

func dryRunRemove(plan removePlan, emitJSON bool) error {
	if emitJSON {
		return writeJSONResult(struct {
			Mode string     `json:"mode"`
			Plan removePlan `json:"plan"`
		}{
			Mode: removeMode(),
			Plan: plan,
		}, nil)
	}

	printRemovePlan(plan)
	return nil
}

func removeMode() string {
	if removeDryRun {
		return "dry-run"
	}
	return "apply"
}

func removeAgentsMD(dir string) error {
	path := filepath.Join(dir, "AGENTS.md")
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !isManagedAgentsContent(string(raw)) {
		return nil // not ours
	}
	return os.Remove(path)
}
