package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/ivanhoe/apus_cli/internal/preflight"
	"github.com/ivanhoe/apus_cli/internal/terminal"
	"github.com/ivanhoe/apus_cli/internal/xcode"
	"github.com/spf13/cobra"
)

var removeDryRun bool
var removeTarget string

var removeCmd = &cobra.Command{
	Use:   "remove",
	Short: "Remove Apus from an existing Xcode project (reverses apus init)",
	Long: `apus remove undoes what apus init did:
removes the Apus Swift Package dependency, the injected import and start() call,
and the AGENTS.md file if it was generated by Apus.`,
	Args: cobra.NoArgs,
	RunE: runRemove,
}

func init() {
	removeCmd.Flags().BoolVar(&removeDryRun, "dry-run", false, "Show what would change without modifying any files")
	removeCmd.Flags().StringVar(&removeTarget, "target", "", "App target to modify when the project contains multiple app targets")
}

func runRemove(_ *cobra.Command, _ []string) error {
	if err := preflight.Validate(preflight.ScopeInit); err != nil {
		return err
	}

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}

	info, err := xcode.DetectProjectWithTarget(cwd, removeTarget)
	if err != nil {
		terminal.Fatal("project detection failed", err)
		return markPrinted(err)
	}

	// Check if Apus is actually integrated
	hasApus, _ := xcode.HasApusIntegration(cwd)
	dependencyState, depErr := xcode.DetectApusDependency(info.ProjectPath)
	if depErr != nil {
		return depErr
	}
	pbxHasApus := dependencyState.Any()

	hasAgents, _ := readManagedAgentsFile(cwd)

	if !hasApus && !pbxHasApus && !hasAgents {
		terminal.Info("Apus is not integrated in this project — nothing to remove.")
		return nil
	}

	terminal.Detected(filepath.Base(info.ProjectPath), info.Target)

	// ── Dry run ──
	if removeDryRun {
		return dryRunRemove(info, hasApus, pbxHasApus, hasAgents)
	}

	backup, err := createProjectBackup(cwd, backupCandidates(info))
	if err != nil {
		return fmt.Errorf("create backup: %w", err)
	}
	if backup.fileCount > 0 {
		terminal.Info("Backup created: " + backup.dir)
	}

	var changes []terminal.FileChange
	p := terminal.NewProgress(3)

	// ── Step 1: Un-inject Swift code ──
	{
		entryLabel := "app entry point"
		if info.EntryFile != "" {
			entryLabel = filepath.Base(info.EntryFile)
		}
		done := p.Start("Removing Apus from " + entryLabel)
		if info.EntryFile != "" {
			entryBefore := countLines(info.EntryFile)
			err = xcode.UninjectApus(info.EntryFile)
			done(err)
			if err != nil {
				terminal.Fatal("Swift un-injection failed", err)
				if rollbackErr := backup.restore(); rollbackErr != nil {
					return fmt.Errorf("swift un-injection failed: %w (rollback failed: %v)", err, rollbackErr)
				}
				return markPrinted(fmt.Errorf("swift un-injection failed; backed-up files restored: %w", err))
			}
			entryAfter := countLines(info.EntryFile)
			if entryAfter != entryBefore {
				changes = append(changes, terminal.FileChange{Action: "modified", File: filepath.Base(info.EntryFile), Detail: fmt.Sprintf("%d lines", entryAfter-entryBefore)})
			}
		} else {
			done(nil)
		}
	}

	// ── Step 2: Remove from .pbxproj ──
	{
		pbxBefore := readFileSize(filepath.Join(info.ProjectPath, "project.pbxproj"))
		done := p.Start("Removing Apus from project.pbxproj")
		err = xcode.RemoveApusDependency(info.ProjectPath, info.Target)
		done(err)
		if err != nil {
			terminal.Fatal("pbxproj modification failed", err)
			if rollbackErr := backup.restore(); rollbackErr != nil {
				return fmt.Errorf("pbxproj modification failed: %w (rollback failed: %v)", err, rollbackErr)
			}
			return markPrinted(fmt.Errorf("pbxproj modification failed; backed-up files restored: %w", err))
		}
		pbxAfter := readFileSize(filepath.Join(info.ProjectPath, "project.pbxproj"))
		if pbxAfter != pbxBefore {
			changes = append(changes, terminal.FileChange{Action: "modified", File: "project.pbxproj", Detail: fmt.Sprintf("%d bytes", pbxAfter-pbxBefore)})
		}
	}

	// ── Step 3: Delete AGENTS.md ──
	{
		done := p.Start("Removing AGENTS.md")
		err = removeAgentsMD(cwd)
		done(err)
		if err != nil {
			terminal.Fatal("AGENTS.md removal failed", err)
			// Non-fatal
		} else if hasAgents {
			changes = append(changes, terminal.FileChange{Action: "deleted", File: "AGENTS.md", Detail: "removed"})
		}
	}

	terminal.Summary(changes)
	terminal.RemoveSuccess(info.ProjectName)
	return nil
}

func dryRunRemove(info *xcode.ProjectInfo, hasSwift, hasPbx, hasAgents bool) error {
	terminal.DryRunHeader()

	if info.EntryFile != "" && hasSwift {
		terminal.DryRunItem("would modify", filepath.Base(info.EntryFile)+" (remove import Apus + Apus.shared.start())")
	} else if info.EntryFile != "" {
		terminal.DryRunItem("skip", filepath.Base(info.EntryFile)+" (no Apus code found)")
	}

	if hasPbx {
		terminal.DryRunItem("would modify", "project.pbxproj (remove Apus SPM dependency)")
	} else {
		terminal.DryRunItem("skip", "project.pbxproj (no Apus dependency found)")
	}

	if hasAgents {
		terminal.DryRunItem("would delete", "AGENTS.md")
	} else {
		terminal.DryRunItem("skip", "AGENTS.md (not found or not generated by Apus)")
	}

	fmt.Println()
	terminal.Info("Run `apus remove` without --dry-run to apply these changes.")
	return nil
}

func removeAgentsMD(dir string) error {
	path := filepath.Join(dir, "AGENTS.md")
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if !isManagedAgentsContent(string(raw)) {
		return nil // not ours
	}
	return os.Remove(path)
}
